### PR TITLE
Update eslint rules for cypress

### PR DESCRIPTION
**Pull request by rdogra-nimble**
Added new rules for cypress based on the cypress recommendation. 
Atm there are only 13 warning and no errors.

### CODE REVIEW

**Comment by jordan-beard** [comment]
When I run the lint with these rules I get a bunch of errors. Unfortunately I think this change will break the CI job.
Unless those errors are fixed or they are set as warnings.
image

**Review by jordan-beard — CHANGES_REQUESTED** [review]
Please see previous comment.

**Comment by rdogra-nimble** [comment]
> Please see previous comment.

Strange! It was giving me only 13 warning. Would have attached a screenshot however screenshot wasn't working on my laptop.
I'll give it a another try.

**Comment by rdogra-nimble** [comment]
Still giving me 13 warnings
lint errors

**Comment by jordan-beard** [comment]
Ah, sorry I copied the rules rather than checking out the branch. After checking out the branch I now get 13 warnings.
Whereas before I had 57, it looks like you made it less strict. Is that the intent with this change?

**Comment by rdogra-nimble** [comment]
Yes, the rules I have put in atm are recommended ones for cypress tests. So starting with those. Few of them are `warning` for which we have a separate ticket to fix and then we can convert them into `error`. And later we could add some more esLint rules.

**Review by jordan-beard — APPROVED** [review]

**Pull request merged**
