### PR TITLE
Rename

### PR DESCRIPTION
**Pull request by jordan-beard**
image

### CODE REVIEW

**Comment by cshnimble** [comment]
Does the .sonarlint folder either need adding to the .gitignore or updating as there's still references to a2b-internal?

**Comment by tim-wilde-nimble** [comment]
I've checked this out locally to be a bit more thorough - having problems running it at the moment. Just diagnosing that. Currently hitting an I/O error.

**Comment by tim-wilde-nimble** [comment]
Resolved - seems the Academisation API had a bit of a slow start - working fine after a refresh.

**Comment by tim-wilde-nimble** [comment]
All builds and runs locally and all (codebase) tests are also passing locally. Ran up and manually navigated through without problems. All 👌 👍 😄

**Review by tim-wilde-nimble — APPROVED** [review]

**Pull request merged**
